// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more
// letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

// solution1: counter O(n) time, O(1) space
class Solution {
  public char findTheDifference(String s, String t) {
    int[] counter = new int[26];
    for (char c : s.toCharArray()) {
      counter[c - 'a']++;
    }
    for (char c : t.toCharArray()) {
      counter[c - 'a']--;
      if (counter[c - 'a'] == -1) return c;
    }
    return 'a';
  }
}

// solution2: xor
